# Site settings
title: AdminTest Blog
SEOTitle: AdminTest blog | AdminTest blog
header-img: img/home_header.png
email: mail_admintest@yeah.com
description: "Hi, I’m AdminTest, a Mobile Developer"
keyword: "AdminTest, TestAdmin, 博客, 个人网站, 互联网, Android, iOS, Swift, Java"
url: "http://www.admintest.top"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username:  AdminTestsGitHub
netease_username: 268494419
keep_username:   563876f01ec5788b089a92b2


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
textColor: #FF0000
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: CN  

# Back to top 回到顶部by ray-eldath
b2t: true

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]
# plugins: [jekyll-sitemap]
paginate_path: "page:num"   #分页页面路径格式



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Comment
#comment:
    #disqus: yizibi

# Netease settings
netease_comment: false

gitalk:
   enable: true
   owner: AdminTest
   repo: http://www.admintest.top
   clientID: 151505dfed32ccfdc391
   clientSecret: 088a9545d55b8f40f0346f03de129f1312ca5e49
   admin: AdminTest


# Analytics settings
# Baidu Analytics 
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900

# Google Analytics
# ga_track_id: 'UA-124793396-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Coder, Passenger, Fresher"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: false



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "友情链接",
        href: "http://www.admintest.top"
    },
    {
        title: "友情链接",
        href: "http://www.admintest.top"
    },
    {
        title: "友情链接",
        href: "http://www.admintest.topm"
    }
]
